version: "3.9"

services:
  mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:33060
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
